// Dummy data for RentEase application

export const properties = [
  {
    id: "1",
    name: "Sunset Apartments",
    address: "123 Ocean Drive, Miami Beach, FL 33139",
    type: "Apartment Complex",
    units: 24,
    occupiedUnits: 22,
    monthlyRent: 48000,
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
  },
  {
    id: "2",
    name: "Downtown Lofts",
    address: "456 Main Street, New York, NY 10001",
    type: "Loft Complex",
    units: 12,
    occupiedUnits: 12,
    monthlyRent: 36000,
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
  },
  {
    id: "3",
    name: "Garden View Townhouses",
    address: "789 Park Avenue, Austin, TX 78701",
    type: "Townhouse",
    units: 8,
    occupiedUnits: 7,
    monthlyRent: 22400,
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
  },
  {
    id: "4",
    name: "Riverside Studios",
    address: "321 River Road, Portland, OR 97201",
    type: "Studio Complex",
    units: 16,
    occupiedUnits: 14,
    monthlyRent: 25600,
    imageUrl: "https://images.unsplash.com/photo-1515263487990-61b07816b324?w=800&h=600&fit=crop",
  },
];

export const tenants = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 123-4567",
    propertyId: "1",
    propertyName: "Sunset Apartments - Unit 12A",
    leaseStart: "2024-01-15",
    leaseEnd: "2025-01-14",
    monthlyRent: 2200,
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "m.chen@email.com",
    phone: "+1 (555) 234-5678",
    propertyId: "2",
    propertyName: "Downtown Lofts - Unit 5B",
    leaseStart: "2023-06-01",
    leaseEnd: "2024-05-31",
    monthlyRent: 3200,
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.r@email.com",
    phone: "+1 (555) 345-6789",
    propertyId: "1",
    propertyName: "Sunset Apartments - Unit 8C",
    leaseStart: "2024-03-01",
    leaseEnd: "2025-02-28",
    monthlyRent: 2100,
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
  },
  {
    id: "4",
    name: "David Martinez",
    email: "david.m@email.com",
    phone: "+1 (555) 456-7890",
    propertyId: "3",
    propertyName: "Garden View Townhouses - Unit 3",
    leaseStart: "2023-09-15",
    leaseEnd: "2024-09-14",
    monthlyRent: 2800,
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
  },
  {
    id: "5",
    name: "Jessica Taylor",
    email: "jessica.t@email.com",
    phone: "+1 (555) 567-8901",
    propertyId: "4",
    propertyName: "Riverside Studios - Unit 9",
    leaseStart: "2024-02-01",
    leaseEnd: "2025-01-31",
    monthlyRent: 1600,
    status: "active",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
  },
];

export const payments = [
  {
    id: "1",
    tenantId: "1",
    tenantName: "Sarah Johnson",
    propertyName: "Sunset Apartments - Unit 12A",
    amount: 2200,
    dueDate: "2024-12-01",
    paidDate: "2024-11-28",
    status: "paid",
    method: "Bank Transfer",
  },
  {
    id: "2",
    tenantId: "2",
    tenantName: "Michael Chen",
    propertyName: "Downtown Lofts - Unit 5B",
    amount: 3200,
    dueDate: "2024-12-01",
    paidDate: "2024-12-01",
    status: "paid",
    method: "Credit Card",
  },
  {
    id: "3",
    tenantId: "3",
    tenantName: "Emily Rodriguez",
    propertyName: "Sunset Apartments - Unit 8C",
    amount: 2100,
    dueDate: "2024-12-01",
    paidDate: null,
    status: "pending",
    method: null,
  },
  {
    id: "4",
    tenantId: "4",
    tenantName: "David Martinez",
    propertyName: "Garden View Townhouses - Unit 3",
    amount: 2800,
    dueDate: "2024-11-15",
    paidDate: null,
    status: "overdue",
    method: null,
  },
  {
    id: "5",
    tenantId: "5",
    tenantName: "Jessica Taylor",
    propertyName: "Riverside Studios - Unit 9",
    amount: 1600,
    dueDate: "2024-12-01",
    paidDate: "2024-11-30",
    status: "paid",
    method: "Bank Transfer",
  },
];

export const utilities = [
  {
    id: "1",
    propertyId: "1",
    propertyName: "Sunset Apartments",
    type: "Electricity",
    provider: "City Power Co.",
    accountNumber: "EP-123456",
    monthlyAverage: 1200,
    lastBillAmount: 1350,
    dueDate: "2024-12-15",
    status: "paid",
  },
  {
    id: "2",
    propertyId: "1",
    propertyName: "Sunset Apartments",
    type: "Water",
    provider: "Municipal Water",
    accountNumber: "WA-789012",
    monthlyAverage: 450,
    lastBillAmount: 480,
    dueDate: "2024-12-10",
    status: "pending",
  },
  {
    id: "3",
    propertyId: "2",
    propertyName: "Downtown Lofts",
    type: "Gas",
    provider: "Metro Gas Services",
    accountNumber: "GS-345678",
    monthlyAverage: 320,
    lastBillAmount: 295,
    dueDate: "2024-12-20",
    status: "paid",
  },
  {
    id: "4",
    propertyId: "3",
    propertyName: "Garden View Townhouses",
    type: "Internet",
    provider: "FastNet ISP",
    accountNumber: "IN-901234",
    monthlyAverage: 180,
    lastBillAmount: 180,
    dueDate: "2024-12-05",
    status: "paid",
  },
];

export const rentTrends = [
  { month: "Jun", collected: 95000, expected: 100000 },
  { month: "Jul", collected: 98000, expected: 102000 },
  { month: "Aug", collected: 102000, expected: 105000 },
  { month: "Sep", collected: 108000, expected: 110000 },
  { month: "Oct", collected: 112000, expected: 115000 },
  { month: "Nov", collected: 118000, expected: 120000 },
];

export const paymentStatusData = [
  { name: "Paid", value: 75, fill: "hsl(var(--success))" },
  { name: "Pending", value: 15, fill: "hsl(var(--warning))" },
  { name: "Overdue", value: 10, fill: "hsl(var(--destructive))" },
];

export const upcomingRentDue = [
  {
    id: "1",
    tenantName: "Sarah Johnson",
    propertyName: "Sunset Apartments - Unit 12A",
    amount: 2200,
    dueDate: "2025-01-01",
    daysUntilDue: 3,
  },
  {
    id: "2",
    tenantName: "Michael Chen",
    propertyName: "Downtown Lofts - Unit 5B",
    amount: 3200,
    dueDate: "2025-01-01",
    daysUntilDue: 3,
  },
  {
    id: "3",
    tenantName: "Jessica Taylor",
    propertyName: "Riverside Studios - Unit 9",
    amount: 1600,
    dueDate: "2025-01-01",
    daysUntilDue: 3,
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Robert Anderson",
    role: "Property Owner",
    content: "RentEase has transformed how I manage my properties. The automated rent tracking and tenant communication features save me hours every week.",
    rating: 5,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
  },
  {
    id: "2",
    name: "Lisa Thompson",
    role: "Landlord",
    content: "The dashboard gives me a complete overview of all my properties at a glance. Payment tracking has never been easier!",
    rating: 5,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
  },
  {
    id: "3",
    name: "James Wilson",
    role: "Real Estate Manager",
    content: "Outstanding platform! The utility management and analytics features help me make better business decisions.",
    rating: 5,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
  },
];
